#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { DISH_RULES } from './recommended_dish_extractor.mjs';

const HERE=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(HERE,'..');
const DATA=path.join(ROOT,'data');
const OUTPUT=process.argv[2]||path.join(ROOT,'_audit','official-jsonld-itemlist-menu.json');
const TIMEOUT_MS=Math.max(6000,Math.min(20000,Number(process.env.OFFICIAL_JSONLD_LIST_TIMEOUT_MS||10000)));
const WORKERS=Math.max(1,Math.min(12,Number(process.env.OFFICIAL_JSONLD_LIST_WORKERS||8)));
const URL_LIMIT=Math.max(1,Math.min(6,Number(process.env.OFFICIAL_JSONLD_LIST_URL_LIMIT||4)));
const USER_AGENT='eat-data-maintenance/2.7 (+https://github.com/nekooweb/eat)';
const NON_HTML=/\.(?:pdf|jpe?g|png|gif|webp|avif|svg|css|js|mjs|xml|zip)(?:$|[?#])/i;
const MENU_URL_CONTEXT=/(?:^|[\/_#?=&-])(?:menu|menus|food|foods|lunch|dinner|dish|dishes|料理|お品書|御品書|メニュー|フード|商品)(?:[\/_#?=&-]|$)/i;
const MENU_TYPE=new Set(['menu','menusection']);

function clean(v){return String(v??'').replace(/\s+/g,' ').trim();}
function decode(v){return String(v??'').replace(/&quot;|&#34;/gi,'"').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').trim();}
function loadRuntime(){const s={window:{},console};vm.createContext(s);vm.runInContext(fs.readFileSync(path.join(DATA,'google_inventory_runtime.js'),'utf8'),s);return{rows:s.window.GOOGLE_INVENTORY_RESTAURANTS||[],stats:s.window.GOOGLE_INVENTORY_STATS||{}};}
function normalizedHost(v){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,'');}catch{return '';}}
function sameHostFamily(a,b){const x=normalizedHost(a),y=normalizedHost(b);return Boolean(x&&y&&(x===y||x.endsWith(`.${y}`)||y.endsWith(`.${x}`)));}
function safeUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||NON_HTML.test(u.toString()))return null;u.hash='';return u.toString();}catch{return null;}}
function typeValues(obj){const raw=obj?.['@type'];return (Array.isArray(raw)?raw:[raw]).map(x=>clean(x).toLowerCase()).filter(Boolean);}
function typeHas(obj,type){return typeValues(obj).some(x=>x===type.toLowerCase()||x.endsWith(`/${type.toLowerCase()}`)||x.endsWith(`:${type.toLowerCase()}`));}
function isMenuContainer(obj){return typeValues(obj).some(x=>MENU_TYPE.has(x)||[...MENU_TYPE].some(t=>x.endsWith(`/${t}`)||x.endsWith(`:${t}`)));}
function menuContextUrl(url){try{const u=new URL(url);return MENU_URL_CONTEXT.test(`${u.pathname}${u.search}${u.hash}`);}catch{return false;}}
function priceEvidence(obj){if(!obj||typeof obj!=='object')return false;const direct=[obj.price,obj.lowPrice,obj.highPrice,obj.priceRange].some(v=>typeof v==='number'||(/\d/.test(clean(v))&&clean(v).length<80));if(direct)return true;const offers=obj.offers;const arr=Array.isArray(offers)?offers:[offers];return arr.some(o=>o&&typeof o==='object'&&[o.price,o.lowPrice,o.highPrice].some(v=>typeof v==='number'||/\d/.test(clean(v))));}
function nameValue(obj){const value=clean(obj?.name||obj?.headline||'');return value.length>=2&&value.length<=180?value:'';}
function asciiFalsePositive(text,match){const token=String(match?.[0]||'');if(!/^[A-Za-z][A-Za-z .'-]*$/.test(token))return false;const start=Number(match?.index??-1);if(start<0)return false;const end=start+token.length;return /[A-Za-z]/.test(start>0?text[start-1]:'')||/[A-Za-z]/.test(end<text.length?text[end]:'');}
function dishMatches(text,limit=8){const value=clean(text),out=[],seen=new Set();for(const [pattern,nameZh] of DISH_RULES){const m=value.match(pattern);if(!m||asciiFalsePositive(value,m)||seen.has(nameZh))continue;seen.add(nameZh);out.push({nameZh,nameOriginal:m[0],rule:pattern.source});if(out.length>=limit)break;}return out;}
function extractJsonLd(html){const out=[],re=/<script\b[^>]*type\s*=\s*['"]application\/ld\+json['"][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(String(html||'')))){const body=decode(m[1]||'');if(!body)continue;try{out.push(JSON.parse(body));}catch{}}return out;}
function flattenGraph(value){const out=[];function walk(v){if(Array.isArray(v)){v.forEach(walk);return;}if(!v||typeof v!=='object')return;out.push(v);if(Array.isArray(v['@graph']))v['@graph'].forEach(walk);}walk(value);return out;}
function candidateEntry(obj,sourceRule){if(!obj||typeof obj!=='object')return null;const item=obj.item&&typeof obj.item==='object'?obj.item:obj;const name=nameValue(item)||nameValue(obj);if(!name||!priceEvidence(item)&&!priceEvidence(obj))return null;if(typeHas(item,'Product')||typeHas(obj,'Product'))return null;return{name,sourceRule};}
function collectListEntries(container,sourceRule){const values=[];for(const key of ['hasMenuSection','hasMenuItem','itemListElement','mainEntity','subjectOf']){const raw=container?.[key];for(const entry of Array.isArray(raw)?raw:[raw]){if(!entry||typeof entry!=='object')continue;const direct=candidateEntry(entry,sourceRule);if(direct)values.push(direct);if(isMenuContainer(entry)||typeHas(entry,'ItemList'))values.push(...collectListEntries(entry,sourceRule));}}return values;}
function extractStructuredMenuEntries(html,url){const output=[];for(const doc of extractJsonLd(html)){for(const obj of flattenGraph(doc)){if(isMenuContainer(obj)){output.push(...collectListEntries(obj,'jsonld-menu-container'));continue;}if(typeHas(obj,'ItemList')&&menuContextUrl(url))output.push(...collectListEntries(obj,'jsonld-menu-context-itemlist'));}}const map=new Map();for(const row of output){const key=`${row.name.toLowerCase()}|${row.sourceRule}`;if(!map.has(key))map.set(key,row);}return[...map.values()];}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(TIMEOUT_MS),headers:{'user-agent':USER_AGENT,accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.1'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ct=r.headers.get('content-type')||'';if(!/text\/html|application\/xhtml\+xml/i.test(ct))throw new Error(`non-html ${ct}`);const finalUrl=r.url||url;if(!sameHostFamily(url,finalUrl))throw new Error(`cross-host redirect ${normalizedHost(url)} -> ${normalizedHost(finalUrl)}`);return{finalUrl,html:(await r.text()).slice(0,2000000)};}

const runtime=loadRuntime();if(runtime.stats.catalogTotal!==2804||runtime.stats.inventoryTotal!==runtime.rows.length)throw new Error('runtime contract mismatch');
const noDish=runtime.rows.filter(r=>!(r.recommendedDishes||[]).length&&!(r.featuredDishes||[]).length),noDishIds=new Set(noDish.map(r=>r.googlePlaceId)),runtimeById=new Map(runtime.rows.map(r=>[r.googlePlaceId,r]));
const official=JSON.parse(fs.readFileSync(path.join(DATA,'reviewed_official_runtime_sources.json'),'utf8'));if(official.policy?.reviewedRowsOnly!==true||official.policy?.conflictRowsPublished!==false||official.policy?.paidGoogleDataApiCalls!==0)throw new Error('reviewed official contract mismatch');
const tasks=[];let reviewedOfficialNoDishRows=0,skippedNonHttpsOrNonHtml=0;
for(const row of official.rows||[]){if(row.reviewState!=='reviewed'||!noDishIds.has(row.googlePlaceId))continue;reviewedOfficialNoDishRows++;const seen=new Set(),urls=[];for(const raw of [...(row.menuUrls||[]),row.pageUrl,...(row.sourceWebsites||[])].filter(Boolean)){const u=safeUrl(raw);if(!u){skippedNonHttpsOrNonHtml++;continue;}if(seen.has(u))continue;seen.add(u);urls.push(u);if(urls.length>=URL_LIMIT)break;}for(const url of urls)tasks.push({googlePlaceId:row.googlePlaceId,name:runtimeById.get(row.googlePlaceId)?.name||'',sourceOfficialName:row.officialName||null,url});}
let cursor=0;const results=[];async function worker(){while(true){const i=cursor++;if(i>=tasks.length)return;const t=tasks[i];try{const page=await fetchHtml(t.url),entries=extractStructuredMenuEntries(page.html,page.finalUrl),featuredDishes=[],seen=new Set();for(const entry of entries){for(const d of dishMatches(entry.name,6)){const k=`${d.nameZh}|${entry.name}|${entry.sourceRule}`;if(seen.has(k))continue;seen.add(k);featuredDishes.push({nameZh:d.nameZh,nameJa:d.nameOriginal,provider:'sourceWebsite',sourceUrl:page.finalUrl,checkedAt:new Date().toISOString().slice(0,10),evidenceClass:'source_menu_text',evidenceRule:`${entry.sourceRule}:${d.rule}`,evidenceSnippet:entry.name.slice(0,120)});}}results.push({...t,finalUrl:page.finalUrl,structuredEntries:entries.length,featuredDishes:featuredDishes.slice(0,8)});}catch(e){results.push({...t,error:String(e?.message||e).slice(0,180),structuredEntries:0,featuredDishes:[]});}}}
await Promise.all(Array.from({length:Math.min(WORKERS,tasks.length||1)},worker));
const byPlace=new Map();for(const r of results){if(!r.featuredDishes.length)continue;const cur=byPlace.get(r.googlePlaceId)||{googlePlaceId:r.googlePlaceId,name:r.name,sourceOfficialName:r.sourceOfficialName,recommendedDishes:[],featuredDishes:[]};for(const d of r.featuredDishes)if(!cur.featuredDishes.some(x=>x.nameZh===d.nameZh&&x.sourceUrl===d.sourceUrl))cur.featuredDishes.push(d);byPlace.set(r.googlePlaceId,cur);}const rows=[...byPlace.values()].sort((a,b)=>a.googlePlaceId.localeCompare(b.googlePlaceId));
const payload={schemaVersion:1,checkedAt:new Date().toISOString().slice(0,10),policy:{auditOnly:true,currentNoDishOnly:true,reviewedOfficialBindingsOnly:true,reviewedOfficialUrlsOnly:true,httpsOnly:true,sameHostFamilyFinalUrlRequired:true,jsonLdMenuOrMenuSectionAccepted:true,itemListAcceptedOnlyOnMenuContextUrl:true,entryNameAndPriceEvidenceRequired:true,productAccepted:false,arbitraryJsonObjectAccepted:false,recommendationPromotionAllowed:false,ordinaryStructuredEntryIsFeaturedOnly:true,identityMutationAllowed:false,catalogNameMutationAllowed:false,sourceOfficialNameRole:'source_alias_only',pageScriptsExecuted:false,rawHtmlPersisted:false,paidGoogleDataApiCalls:0},summary:{catalogTotal:2804,publicRuntimeTotal:runtime.rows.length,currentNoDish:noDish.length,reviewedOfficialNoDishRows,htmlTasks:tasks.length,skippedNonHttpsOrNonHtml,pagesFetched:results.filter(r=>!r.error).length,errorPages:results.filter(r=>r.error).length,pagesWithStructuredMenuEntries:results.filter(r=>r.structuredEntries>0).length,structuredMenuEntries:results.reduce((s,r)=>s+r.structuredEntries,0),evidenceRestaurants:rows.length,featuredItems:rows.reduce((s,r)=>s+r.featuredDishes.length,0)},rows,diagnostics:results.map(r=>({googlePlaceId:r.googlePlaceId,name:r.name,url:r.url,finalUrl:r.finalUrl||null,structuredEntries:r.structuredEntries,featuredItems:r.featuredDishes.length,error:r.error||null}))};
fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(payload,null,2)+'\n','utf8');console.log(JSON.stringify(payload.summary));if(rows.length)console.log('JSONLD_LIST_EVIDENCE_SAMPLES='+JSON.stringify(rows.slice(0,20)));
