#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { DISH_RULES } from './recommended_dish_extractor.mjs';

const HERE=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(HERE,'..');
const DATA=path.join(ROOT,'data');
const OUTPUT=process.argv[2]||path.join(ROOT,'_audit','official-rdfa-menu-items.json');
const TIMEOUT_MS=Math.max(6000,Math.min(20000,Number(process.env.OFFICIAL_RDFA_TIMEOUT_MS||10000)));
const WORKERS=Math.max(1,Math.min(12,Number(process.env.OFFICIAL_RDFA_WORKERS||8)));
const URL_LIMIT=Math.max(1,Math.min(6,Number(process.env.OFFICIAL_RDFA_URL_LIMIT||4)));
const USER_AGENT='eat-data-maintenance/2.6 (+https://github.com/nekooweb/eat)';
const NON_HTML=/\.(?:pdf|jpe?g|png|gif|webp|avif|svg|css|js|mjs|xml|zip)(?:$|[?#])/i;

function clean(v){return String(v??'').replace(/\s+/g,' ').trim();}
function decode(v){return String(v??'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>{const c=Number(n);return Number.isFinite(c)&&c>0&&c<=0x10ffff?String.fromCodePoint(c):' ';});}
function stripTags(v){return clean(decode(String(v??'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')));}
function attr(attrs,name){return decode((String(attrs||'').match(new RegExp(`\\b${name}\\s*=\\s*(["'])(.*?)\\1`,'i'))||[])[2]||'');}
function propHas(attrs,token){return attr(attrs,'property').split(/\s+/).some(x=>x.toLowerCase()===token.toLowerCase());}
function isMenuItemType(attrs){const type=attr(attrs,'typeof');return type.split(/\s+/).some(x=>/^(?:schema:)?MenuItem$/i.test(x)||/schema\.org\/MenuItem$/i.test(x));}
function normalizedHost(v){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,'');}catch{return '';}}
function sameHostFamily(a,b){const x=normalizedHost(a),y=normalizedHost(b);return Boolean(x&&y&&(x===y||x.endsWith(`.${y}`)||y.endsWith(`.${x}`)));}
function safeUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||NON_HTML.test(u.toString()))return null;u.hash='';return u.toString();}catch{return null;}}
function loadRuntime(){const s={window:{},console};vm.createContext(s);vm.runInContext(fs.readFileSync(path.join(DATA,'google_inventory_runtime.js'),'utf8'),s);return{rows:s.window.GOOGLE_INVENTORY_RESTAURANTS||[],stats:s.window.GOOGLE_INVENTORY_STATS||{}};}
function asciiFalsePositive(text,match){const token=String(match?.[0]||'');if(!/^[A-Za-z][A-Za-z .'-]*$/.test(token))return false;const start=Number(match?.index??-1);if(start<0)return false;const end=start+token.length;return /[A-Za-z]/.test(start>0?text[start-1]:'')||/[A-Za-z]/.test(end<text.length?text[end]:'');}
function dishMatches(text,limit=8){const value=clean(text),out=[],seen=new Set();for(const [pattern,nameZh] of DISH_RULES){const m=value.match(pattern);if(!m||asciiFalsePositive(value,m)||seen.has(nameZh))continue;seen.add(nameZh);out.push({nameZh,nameOriginal:m[0],rule:pattern.source});if(out.length>=limit)break;}return out;}
function nameValues(block){const out=[],seen=new Set();const re=/<([a-z][a-z0-9:-]*)\b([^>]*)>([\s\S]*?)<\/\1\s*>|<(meta)\b([^>]*)\/?>/gi;let m;while((m=re.exec(block))){const attrs=m[2]??m[5]??'';if(!propHas(attrs,'name'))continue;let value=m[4]?attr(attrs,'content'):(attr(attrs,'content')||stripTags(m[3]));value=clean(value);if(value.length<2||value.length>160||seen.has(value))continue;seen.add(value);out.push(value);}return out;}
function extractRdfaMenuItems(html){const text=String(html||''),opens=[],re=/<([a-z][a-z0-9:-]*)\b([^>]*)>/gi;let m;while((m=re.exec(text))){if(!isMenuItemType(m[2]||''))continue;opens.push({tag:m[1],start:re.lastIndex,openIndex:m.index});}const rows=[];for(let i=0;i<opens.length;i++){const cur=opens[i],next=opens[i+1]?.openIndex??text.length;const close=new RegExp(`<\\/${cur.tag}\\s*>`,'ig');close.lastIndex=cur.start;const cm=close.exec(text);const end=Math.min(cm?cm.index:cur.start+12000,next>cur.start?next:text.length,cur.start+12000);for(const name of nameValues(text.slice(cur.start,Math.max(cur.start,end))))rows.push({name});}const map=new Map();for(const r of rows){const k=r.name.toLowerCase();if(!map.has(k))map.set(k,r);}return[...map.values()];}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(TIMEOUT_MS),headers:{'user-agent':USER_AGENT,accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.1'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ct=r.headers.get('content-type')||'';if(!/text\/html|application\/xhtml\+xml/i.test(ct))throw new Error(`non-html ${ct}`);const finalUrl=r.url||url;if(!sameHostFamily(url,finalUrl))throw new Error(`cross-host redirect ${normalizedHost(url)} -> ${normalizedHost(finalUrl)}`);return{finalUrl,html:(await r.text()).slice(0,2000000)};}

const runtime=loadRuntime();
if(runtime.stats.catalogTotal!==2804||runtime.stats.inventoryTotal!==runtime.rows.length)throw new Error('runtime contract mismatch');
const noDish=runtime.rows.filter(r=>!(r.recommendedDishes||[]).length&&!(r.featuredDishes||[]).length),noDishIds=new Set(noDish.map(r=>r.googlePlaceId)),runtimeById=new Map(runtime.rows.map(r=>[r.googlePlaceId,r]));
const official=JSON.parse(fs.readFileSync(path.join(DATA,'reviewed_official_runtime_sources.json'),'utf8'));
if(official.policy?.reviewedRowsOnly!==true||official.policy?.conflictRowsPublished!==false||official.policy?.paidGoogleDataApiCalls!==0)throw new Error('reviewed official contract mismatch');
const tasks=[];let reviewedOfficialNoDishRows=0,skippedNonHttpsOrNonHtml=0;
for(const row of official.rows||[]){if(row.reviewState!=='reviewed'||!noDishIds.has(row.googlePlaceId))continue;reviewedOfficialNoDishRows++;const seen=new Set(),urls=[];for(const raw of [...(row.menuUrls||[]),row.pageUrl,...(row.sourceWebsites||[])].filter(Boolean)){const u=safeUrl(raw);if(!u){skippedNonHttpsOrNonHtml++;continue;}if(seen.has(u))continue;seen.add(u);urls.push(u);if(urls.length>=URL_LIMIT)break;}for(const url of urls)tasks.push({googlePlaceId:row.googlePlaceId,name:runtimeById.get(row.googlePlaceId)?.name||'',sourceOfficialName:row.officialName||null,url});}
let cursor=0;const results=[];async function worker(){while(true){const i=cursor++;if(i>=tasks.length)return;const t=tasks[i];try{const page=await fetchHtml(t.url),scopes=extractRdfaMenuItems(page.html),featuredDishes=[],seen=new Set();for(const scope of scopes){for(const d of dishMatches(scope.name,6)){const k=`${d.nameZh}|${scope.name}`;if(seen.has(k))continue;seen.add(k);featuredDishes.push({nameZh:d.nameZh,nameJa:d.nameOriginal,provider:'sourceWebsite',sourceUrl:page.finalUrl,checkedAt:new Date().toISOString().slice(0,10),evidenceClass:'source_menu_text',evidenceRule:`rdfa-menuitem:${d.rule}`,evidenceSnippet:scope.name.slice(0,120)});}}results.push({...t,finalUrl:page.finalUrl,rdfaMenuItemScopes:scopes.length,featuredDishes:featuredDishes.slice(0,8)});}catch(e){results.push({...t,error:String(e?.message||e).slice(0,180),rdfaMenuItemScopes:0,featuredDishes:[]});}}}
await Promise.all(Array.from({length:Math.min(WORKERS,tasks.length||1)},worker));
const byPlace=new Map();for(const r of results){if(!r.featuredDishes.length)continue;const cur=byPlace.get(r.googlePlaceId)||{googlePlaceId:r.googlePlaceId,name:r.name,sourceOfficialName:r.sourceOfficialName,recommendedDishes:[],featuredDishes:[]};for(const d of r.featuredDishes)if(!cur.featuredDishes.some(x=>x.nameZh===d.nameZh&&x.sourceUrl===d.sourceUrl))cur.featuredDishes.push(d);byPlace.set(r.googlePlaceId,cur);}
const rows=[...byPlace.values()].sort((a,b)=>a.googlePlaceId.localeCompare(b.googlePlaceId));
const payload={schemaVersion:1,checkedAt:new Date().toISOString().slice(0,10),policy:{auditOnly:true,currentNoDishOnly:true,reviewedOfficialBindingsOnly:true,reviewedOfficialUrlsOnly:true,httpsOnly:true,sameHostFamilyFinalUrlRequired:true,explicitSchemaOrgRdfaMenuItemOnly:true,schemaOrgProductAccepted:false,arbitraryVisibleTextAccepted:false,recommendationPromotionAllowed:false,ordinaryMenuItemIsFeaturedOnly:true,identityMutationAllowed:false,catalogNameMutationAllowed:false,sourceOfficialNameRole:'source_alias_only',pageScriptsExecuted:false,rawHtmlPersisted:false,paidGoogleDataApiCalls:0},summary:{catalogTotal:2804,publicRuntimeTotal:runtime.rows.length,currentNoDish:noDish.length,reviewedOfficialNoDishRows,htmlTasks:tasks.length,skippedNonHttpsOrNonHtml,pagesFetched:results.filter(r=>!r.error).length,errorPages:results.filter(r=>r.error).length,pagesWithRdfaMenuItem:results.filter(r=>r.rdfaMenuItemScopes>0).length,rdfaMenuItemScopes:results.reduce((s,r)=>s+r.rdfaMenuItemScopes,0),evidenceRestaurants:rows.length,featuredItems:rows.reduce((s,r)=>s+r.featuredDishes.length,0)},rows,diagnostics:results.map(r=>({googlePlaceId:r.googlePlaceId,name:r.name,url:r.url,finalUrl:r.finalUrl||null,rdfaMenuItemScopes:r.rdfaMenuItemScopes,featuredItems:r.featuredDishes.length,error:r.error||null}))};
fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(payload,null,2)+'\n','utf8');console.log(JSON.stringify(payload.summary));if(rows.length)console.log('RDFA_EVIDENCE_SAMPLES='+JSON.stringify(rows.slice(0,20)));
