#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { FEATURED_TEMPLATES } from './featured_template_registry.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'data');
const OUTPUT = process.argv[2] || path.join(DATA, 'source_enrichment_zzzzzfeaturedtemplates.js');
const CHECKED_AT = process.env.FEATURED_TEMPLATE_CHECKED_AT || new Date().toISOString().slice(0, 10);

function loadProduction() {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(path.join(DATA, 'production_area1.js'), 'utf8'), sandbox, { filename:'production_area1.js' });
  return sandbox.window.PRODUCTION_RESTAURANTS || [];
}

function loadResolutionIds() {
  const files = fs.readdirSync(DATA).filter((name)=>/^source_resolution(?:_[a-z0-9-]+)?\.js$/i.test(name)).sort();
  const sandbox = { window: { SOURCE_RESOLUTIONS: [] } };
  vm.createContext(sandbox);
  for (const file of files) vm.runInContext(fs.readFileSync(path.join(DATA,file),'utf8'), sandbox, { filename:file });
  return new Set((sandbox.window.SOURCE_RESOLUTIONS || []).map((row)=>row.googlePlaceId).filter(Boolean));
}

function isSourceBacked(row) {
  return Array.isArray(row.sources) && row.sources.some((source)=>source !== 'OpenStreetMap');
}

function js(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

const production = loadProduction();
const resolutionIds = loadResolutionIds();
const patches = [];
const blocked = [];

for (const row of production) {
  if (Array.isArray(row.featuredDishes) && row.featuredDishes.length) continue;
  const template = FEATURED_TEMPLATES.find((candidate)=>candidate.re.test(String(row.name || '')));
  if (!template) continue;
  if (resolutionIds.has(row.googlePlaceId)) {
    blocked.push({googlePlaceId:row.googlePlaceId,name:row.name,brand:template.key,reason:'source_resolution'});
    continue;
  }
  if (!isSourceBacked(row)) {
    blocked.push({googlePlaceId:row.googlePlaceId,name:row.name,brand:template.key,reason:'not_source_backed'});
    continue;
  }
  patches.push({
    googlePlaceId: row.googlePlaceId,
    name: row.name,
    brand: template.key,
    sourceUrl: template.source,
    legacyDishes: template.legacy,
    featuredDishes: template.featured
  });
}

const lines = [];
lines.push('// Generated by reusing already-reviewed brand-menu featured-dish templates.');
lines.push('// Only exact production identities that are already independently source-backed and unresolved are eligible.');
lines.push(`const FEATURED_TEMPLATE_CHECKED_AT = ${js(CHECKED_AT)};`);
lines.push(`const featuredTemplatePatches = ${JSON.stringify(patches, null, 2)};`);
lines.push('window.FEATURED_DISHES = Array.isArray(window.FEATURED_DISHES) ? window.FEATURED_DISHES : [];');
lines.push('for (const patch of featuredTemplatePatches) {');
lines.push("  let row=[...window.RESTAURANTS].reverse().find((item)=>item&&item.googlePlaceId===patch.googlePlaceId&&item.source==='official'&&item.sourceOnly);");
lines.push("  if(!row){row={id:`src-featured-template-${patch.googlePlaceId.slice(-12).replace(/[^A-Za-z0-9_-]/g,'')}`,profile:'TOKYO',area:'地区1️⃣',name:patch.name,googlePlaceId:patch.googlePlaceId,source:'official',sourceOnly:true,sourceRefs:[]};window.RESTAURANTS.push(row);}");
lines.push('  row.name=patch.name;');
lines.push('  row.dishes=[...new Set([...(Array.isArray(row.dishes)?row.dishes:[]),...patch.legacyDishes])].slice(0,4);');
lines.push("  row.sourceRefs=Array.isArray(row.sourceRefs)?row.sourceRefs:[]; row.sourceRefs=row.sourceRefs.map((ref)=>ref&&ref.provider==='official'?{...ref,fields:(ref.fields||[]).filter((field)=>field!=='dishes')}:ref).filter((ref)=>ref&&(ref.provider!=='official'||(ref.fields||[]).length));");
lines.push("  row.sourceRefs.push({provider:'official',url:patch.sourceUrl,checkedAt:FEATURED_TEMPLATE_CHECKED_AT,fields:['dishes']});");
lines.push('  window.FEATURED_DISHES.push({googlePlaceId:patch.googlePlaceId,sourceUrl:patch.sourceUrl,checkedAt:FEATURED_TEMPLATE_CHECKED_AT,dishes:patch.featuredDishes});');
lines.push('}');
lines.push('');

fs.writeFileSync(OUTPUT, `${lines.join('\n')}\n`, 'utf8');
console.log(JSON.stringify({
  productionEntities: production.length,
  templateBrands: FEATURED_TEMPLATES.length,
  promoted: patches.length,
  patches: patches.map((row)=>({googlePlaceId:row.googlePlaceId,name:row.name,brand:row.brand,sourceUrl:row.sourceUrl})),
  blocked: blocked.length,
  blockedReasons: blocked.reduce((acc,row)=>{acc[row.reason]=(acc[row.reason]||0)+1;return acc;},{}),
  blockedRows: blocked
}));
