// Curated Japanese -> zh-CN normalization used ONLY for exact-bound Hot Pepper
// h3 headings inside an explicit h2 おすすめ料理 section.
//
// These rules intentionally do not join the global dish dictionary. Some source
// terms (for example 牡蠣, 火鍋, 干物) are safe only because the surrounding
// Hot Pepper structure already establishes that the h3 is a restaurant
// recommendation item. No cuisine, brand, restaurant-name or proximity inference
// is performed here.

const RULES = [
  [/生牡蠣カン缶焼き/i, '罐烤牡蛎', 'oyster-can-grill', 'oyster'],
  [/牡蠣/i, '牡蛎', 'oyster', 'oyster'],
  [/鯛ごま丼/i, '鲷鱼芝麻盖饭', 'tai-goma-don'],
  [/海鮮贅沢丼/i, '豪华海鲜盖饭', 'luxury-seafood-don'],
  [/本まぐろぶつ|マグロぶつ切り|鮪ぶつ切り/i, '金枪鱼切块', 'tuna-butsu'],
  [/日替わり定食/i, '每日定食', 'daily-set-meal'],
  [/パーティープレート/i, '派对拼盘', 'party-plate'],
  [/トルティーヤ/i, '墨西哥薄饼', 'tortilla'],
  [/和牛カルビ/i, '和牛肋肉', 'wagyu-kalbi'],
  [/コプチャン/i, '韩式烤牛小肠', 'gopchang'],
  [/豚タン/i, '猪舌', 'pork-tongue'],
  [/手羽先/i, '鸡翅', 'chicken-wing'],
  [/フロマージュ\s*3種盛り合わせ|チーズ盛り合わせ|チーズ盛り合せ/i, '奶酪拼盘', 'cheese-platter'],
  [/キッシュ/i, '法式咸派', 'quiche'],
  [/ソーセージ/i, '香肠', 'sausage'],
  [/ナックチ炒め/i, '辣炒章鱼', 'nakji-bokkeum'],
  [/ポッサム/i, '韩式菜包肉', 'bossam'],
  [/レーズンバター/i, '葡萄干黄油', 'raisin-butter'],
  [/石焼(?:本場)?(?:マーボー|麻婆)豆(?:腐)?/i, '石锅麻婆豆腐', 'stone-mapotofu'],
  [/季節の土鍋ご飯|土鍋ご飯/i, '土锅饭', 'donabe-rice', 'donabe-rice'],
  [/海鮮刺し盛り/i, '海鲜刺身拼盘', 'seafood-sashimi-platter'],
  [/刺盛り/i, '刺身拼盘', 'sashimi-platter'],
  [/とり天/i, '鸡肉天妇罗', 'toriten'],
  [/パテ[・･]ド[・･]カンパーニュ/i, '法式乡村肉酱', 'pate-de-campagne'],
  [/デザートプレート/i, '甜点拼盘', 'dessert-plate'],
  [/自然生のふわとろ鉄板焼き/i, '铁板烤山药', 'jinenjo-teppan'],
  [/自然薯のすりおろし生とろ/i, '生磨山药泥', 'grated-jinenjo'],
  [/スペイン産イベリコ豚の生ハム/i, '伊比利亚生火腿', 'iberico-ham', 'raw-ham'],
  [/生ハム/i, '生火腿', 'raw-ham', 'raw-ham'],
  [/ナポリタン/i, '日式拿坡里意面', 'napolitan'],
  [/上タン塩/i, '上等盐味牛舌', 'premium-salted-tongue', 'premium-tongue'],
  [/上タン(?!塩)/i, '上等牛舌', 'premium-tongue', 'premium-tongue'],
  [/肉三種盛り/i, '三种肉拼盘', 'three-meat-platter'],
  [/季節御膳/i, '时令御膳', 'seasonal-gozen'],
  [/薬膳火鍋/i, '药膳火锅', 'herbal-hotpot', 'hotpot'],
  [/火鍋/i, '火锅', 'hotpot', 'hotpot'],
  [/北京ダック/i, '北京烤鸭', 'peking-duck'],
  [/フカヒレ(?:の)?姿煮(?:込み)?/i, '红烧整翅', 'whole-shark-fin'],
  [/フカヒレスープ/i, '鱼翅汤', 'shark-fin-soup'],
  [/麻辣豆腐/i, '麻辣豆腐', 'mala-tofu'],
  [/海老のマヨネーズソース和え/i, '蛋黄酱虾', 'shrimp-mayo'],
  [/大山鶏もも香味炙り/i, '香炙大山鸡腿肉', 'daisen-chicken-aburi'],
  [/干物/i, '日式鱼干', 'himono'],
  [/馬肉のたたき/i, '炙烤马肉', 'horse-tataki'],
  [/桜ユッケ/i, '生拌马肉', 'sakura-yukhoe'],
  [/鹿ユッケ風/i, '生拌鹿肉', 'venison-yukhoe'],
  [/(?:銘柄豚)?ひれかつ定食/i, '炸猪里脊定食', 'hirekatsu-set'],
  [/(?:銘柄豚)?ロースかつ定食/i, '炸猪排定食', 'rosukatsu-set'],
  [/海老かつ定食/i, '炸虾排定食', 'shrimp-katsu-set'],
  [/鳥すき鍋|かしわ鍋/i, '鸡肉寿喜锅', 'chicken-sukiyaki'],
  [/ポテトサラダ|ぽてさら/i, '土豆沙拉', 'potato-salad', 'potato-salad'],
  [/焼たん/i, '烤牛舌', 'grilled-tongue'],
  [/ゆでたん/i, '水煮牛舌', 'boiled-tongue'],
  [/白レバー/i, '白肝', 'white-liver'],
  [/鶏漬け南蛮/i, '腌鸡南蛮', 'marinated-chicken-nanban'],
  [/鶏ももタタキ/i, '炙拌鸡腿肉', 'chicken-thigh-tataki'],
  [/とり皮ポン酢/i, '柚子醋鸡皮', 'chicken-skin-ponzu'],
  [/がつ刺し/i, '猪肚刺身', 'gatsu-sashi'],
  [/ラビオリ/i, '意式饺子', 'ravioli'],
  [/霜降り馬刺し/i, '霜降马肉刺身', 'marbled-horse-sashimi', 'horse-sashimi'],
  [/馬刺し/i, '马肉刺身', 'horse-sashimi', 'horse-sashimi'],
  [/石焼牛レバー/i, '石烤牛肝', 'stone-grilled-beef-liver'],
  [/地鶏の鉄板焼き/i, '铁板烧地鸡', 'jidori-teppan'],
  [/鶏刺し盛り合わせ/i, '鸡肉刺身拼盘', 'chicken-sashimi-platter'],
  [/魚介のリングイネ\s*トマトクリームソース|リングイネ\s*トマトクリームソース/i, '海鲜番茄奶油扁面', 'seafood-linguine'],
  [/和牛のカルパッチョ/i, '和牛薄切冷盘', 'wagyu-carpaccio'],
  [/炙り〆鯖/i, '炙烤醋腌鲭鱼', 'aburi-shimesaba'],
  [/カブト煮/i, '鱼头炖煮', 'kabuto-ni'],
  [/大正海老の四川風炒め/i, '川味炒大正虾', 'sichuan-taisho-shrimp'],
  [/うな丼ダブル/i, '双层鳗鱼盖饭', 'double-unadon'],
  [/うな重/i, '鳗鱼重', 'unaju'],
  [/ひつまぶし/i, '鳗鱼三吃饭', 'hitsumabushi'],
  [/ジェノベーゼ/i, '热那亚青酱意面', 'genovese-pasta'],
  [/ゴーヤちゃんぷる/i, '苦瓜炒什锦', 'goya-champuru'],
  [/ラフテー/i, '冲绳红烧猪肉', 'rafute'],
  [/フィッシュ[＆&]チップス/i, '炸鱼薯条', 'fish-and-chips'],
  [/コテージパイ/i, '牛肉土豆派', 'cottage-pie'],
  [/コロネーションチキン/i, '加冕鸡', 'coronation-chicken'],
  [/サバの味噌煮/i, '味噌煮鲭鱼', 'miso-simmered-mackerel'],
  [/揚げ物盛り合わせ/i, '炸物拼盘', 'fried-platter'],
  [/のどぐろ焼き/i, '烤赤鯥', 'grilled-nodoguro'],
  [/国産和牛サーロインのタリアータ/i, '国产和牛西冷塔利亚塔', 'wagyu-tagliata'],
  [/ヨウポー麺/i, '油泼面', 'youpo-noodles'],
  [/マーラー麺/i, '麻辣汤面', 'mala-noodles'],
  [/ネギタン塩/i, '葱盐牛舌', 'negi-salted-tongue'],
  [/プレミアにぎり/i, '豪华握寿司', 'premium-nigiri'],
  [/厚焼き玉子/i, '厚烧玉子', 'atsuyaki-tamago'],
  [/鴨葱焼き/i, '葱烤鸭肉', 'duck-negi-grill'],
  [/焼きすき/i, '烤寿喜', 'yaki-suki'],
  [/鴨・馬刺し\s*四種\s*盛り合わせ/i, '鸭肉与马肉刺身四种拼盘', 'duck-horse-sashimi-platter'],
  [/鴨しゃぶ/i, '鸭肉涮锅', 'duck-shabu'],
  [/イベリコ豚の岩塩焼/i, '岩盐烤伊比利亚猪', 'iberico-rocksalt-grill'],
  [/マグロとアボカドと長芋のタルタル/i, '金枪鱼牛油果山药塔塔', 'tuna-avocado-tartare'],
  [/前菜盛り合(?:せ|わせ)/i, '前菜拼盘', 'appetizer-platter'],
  [/スペイン風オムレツ/i, '西班牙煎蛋卷', 'spanish-omelet', 'omelet'],
  [/本日のオムレツ/i, '西式煎蛋卷', 'omelet', 'omelet'],
  [/ガーリックシュリンプ/i, '蒜香虾', 'garlic-shrimp'],
  [/炭バーグ/i, '炭烤汉堡肉排', 'charcoal-hamburg'],
  [/豚の角煮.{0,8}上海風|上海風角煮/i, '上海风红烧肉', 'shanghai-pork-belly'],
  [/スペアリブの甘酢煮込み/i, '糖醋炖排骨', 'sweet-sour-ribs'],
  [/空芯菜/i, '炒空心菜', 'water-spinach'],
  [/肉まん/i, '肉包', 'nikuman'],
  [/かつおの藁焼き\s*塩たたき/i, '盐味稻草炙烤鲣鱼', 'straw-seared-bonito'],
  [/季節のフルーツとブラッターチーズ/i, '时令水果布拉塔奶酪', 'fruit-burrata'],
  [/シャケといくらの土鍋/i, '鲑鱼鲑鱼子土锅饭', 'salmon-ikura-donabe'],
  [/特製もつ煮込/i, '特制炖内脏', 'special-motsuni', 'motsuni'],
  [/もつ煮/i, '炖内脏', 'motsuni', 'motsuni'],
  [/酸辣拌麺/i, '酸辣拌面', 'sour-spicy-mixed-noodles'],
  [/カムジャタン/i, '韩式土豆排骨汤', 'gamjatang'],
  [/タッカンマリ/i, '韩式一只鸡锅', 'dakhanmari'],
  [/完熟チョコバナナハニトー/i, '巧克力香蕉蜂蜜吐司', 'choco-banana-honey-toast'],
  [/アフタヌーンティーセット/i, '下午茶套餐', 'afternoon-tea-set'],
  [/アクアパッツ[ァア]/i, '意式水煮鱼', 'acqua-pazza'],
  [/タン元食べ比べ/i, '牛舌根拼盘', 'tongue-root-tasting'],
  [/焼売|シウマイ/i, '烧卖', 'shumai', 'shumai'],
  [/海ブドウ/i, '海葡萄', 'sea-grapes'],
  [/肉盛りプレート/i, '肉类拼盘', 'meat-plate'],
  [/上海蟹味噌ソース炒め/i, '上海蟹酱炒扇贝', 'shanghai-crab-sauce-scallop', 'shanghai-crab'],
  [/上海蟹/i, '上海蟹', 'shanghai-crab', 'shanghai-crab'],
  [/乞食鶏/i, '叫花鸡', 'beggars-chicken'],
  [/アボカドと季節のフルーツの生春巻き/i, '牛油果时令水果生春卷', 'avocado-fruit-spring-roll'],
  [/アボカドと海老のアヒージョ/i, '牛油果虾蒜油煮', 'avocado-shrimp-ajillo', 'ajillo'],
  [/アボカドとクリームチーズのわさび醤油和え/i, '牛油果奶油奶酪芥末酱油拌', 'avocado-cream-cheese-wasabi'],
  [/九州地鶏のもも焼き/i, '烤九州地鸡腿肉', 'kyushu-chicken-thigh'],
  [/ネギーチャーシュー/i, '葱叉烧', 'negi-chashu'],
  [/乾焼鮮蝦仁|芝えびの唐辛子ソース煮/i, '干烧虾仁', 'chili-shrimp'],
  [/冷鮮鮑魚|あわびの薄切り冷菜/i, '鲍鱼冷盘', 'abalone-cold-dish'],
  [/おまかせ6串/i, '主厨精选六串', 'six-skewers'],
  [/霜降りささみと三つ葉の山葵醤油和え/i, '鸡柳鸭儿芹芥末酱油拌', 'sasami-mitsuba-wasabi'],
  [/海鮮玉/i, '海鲜大阪烧', 'seafood-okonomiyaki'],
  [/大山地鶏の半身揚げ/i, '炸半只大山地鸡', 'half-fried-daisen-chicken'],
  [/食べる辣油のキムチ鍋/i, '辣油泡菜锅', 'rayu-kimchi-hotpot'],
  [/阿波尾鶏と大山地鶏の食べ比べ/i, '阿波尾鸡与大山地鸡拼盘', 'awaodori-daisen-tasting'],
  [/パクチーメンマ/i, '香菜笋干', 'coriander-menma'],
  [/黒豚シウマイ/i, '黑猪肉烧卖', 'black-pork-shumai', 'shumai'],
  [/牛すじ豆腐/i, '牛筋豆腐', 'beef-tendon-tofu'],
  [/信州サーモン/i, '信州三文鱼', 'shinshu-salmon'],
  [/あて巻き/i, '酒肴卷寿司', 'atemaki'],
  [/トマトタンメン/i, '番茄汤面', 'tomato-tanmen'],
  [/チキンバスケット/i, '炸鸡篮', 'chicken-basket'],
  [/アイスバイン/i, '德式咸猪肘', 'eisbein'],
  [/シェパーズパイ/i, '牧羊人派', 'shepherds-pie'],
  [/ガーリックスペアリブ/i, '蒜香排骨', 'garlic-ribs'],
  [/エビのXO醤春雨煮/i, 'XO酱虾粉丝煲', 'xo-shrimp-vermicelli'],
  [/いくらのせ鉄板巻き出汁玉子/i, '鲑鱼子铁板卷高汤玉子烧', 'ikura-dashimaki', 'dashimaki'],
  [/スペアリブの黒酢煮/i, '黑醋炖排骨', 'black-vinegar-ribs'],
  [/豚角煮丼/i, '红烧猪肉盖饭', 'kakuni-don'],
  [/レバー◆|レバー.{0,12}串/i, '烤肝串', 'liver-skewer'],
  [/せせり◆|せせり.{0,12}串/i, '烤鸡颈肉串', 'seseri-skewer'],
  [/肉4種の盛り合わせ/i, '四种肉拼盘', 'four-meat-platter'],
  [/シャルキュトリー盛り合わせ/i, '法式肉类冷盘', 'charcuterie-platter'],
  [/本マグロ定番盛/i, '蓝鳍金枪鱼拼盘', 'bluefin-tuna-platter'],
  [/だし巻玉子|出汁玉子/i, '日式高汤玉子烧', 'dashimaki', 'dashimaki'],
  [/とりハラミ炭火焼き/i, '炭烤鸡横膈膜', 'charcoal-chicken-harami'],
  [/たこさんウィンナー/i, '章鱼造型香肠', 'octopus-sausage'],
  [/キンキの煮付け/i, '酱煮喜知次鱼', 'simmered-kinki'],
  [/おまかせにぎり/i, '主厨精选握寿司', 'omakase-nigiri'],
  [/玉子焼き/i, '玉子烧', 'tamagoyaki'],
  [/肉じゃが/i, '日式土豆炖肉', 'nikujaga'],
  [/上ハラミ/i, '上等牛横膈膜', 'premium-harami'],
  [/上バラ/i, '上等牛五花', 'premium-bara'],
  [/シュラスコ/i, '巴西烤肉', 'churrasco'],
  [/鮮魚のカルパッチョ/i, '鲜鱼薄切冷盘', 'fish-carpaccio'],
  [/産直野菜のグリル/i, '烤直采蔬菜', 'grilled-farm-vegetables'],
  [/ポテトサラダ/i, '土豆沙拉', 'potato-salad-broad', 'potato-salad'],
  [/魅惑のおさかなユッケ|おさかなユッケ/i, '鱼肉生拌', 'fish-yukhoe'],
  [/錦爽鶏/i, '锦爽鸡拼盘', 'kinsodori-platter'],
  [/たまり漬けチーズ/i, '酱油腌渍奶酪', 'tamari-cheese'],
  [/イカの塩辛/i, '盐辛鱿鱼', 'shiokara-squid'],
  [/白味噌バーニャカウダ/i, '白味噌蒜香热蘸蔬菜', 'white-miso-bagna-cauda'],
  [/サイフォン出汁巻き/i, '虹吸高汤玉子烧', 'siphon-dashimaki', 'dashimaki'],
  [/魚介のパエリア|具沢山魚介のパエリア/i, '海鲜西班牙饭', 'seafood-paella'],
  [/アヒージョ/i, '西班牙蒜油煮', 'ajillo', 'ajillo'],
  [/炙り明太子/i, '炙烤明太子', 'aburi-mentaiko'],
  [/牛スジ煮込み/i, '炖牛筋', 'beef-tendon-stew'],
  [/オリーブ牛のグリル/i, '烤橄榄牛', 'olive-beef-grill'],
  [/点心/i, '点心', 'dim-sum']
];

export const HOTPEPPER_EXPLICIT_RECOMMENDATION_RULES = RULES;

export function normalizeExplicitHotPepperRecommendationHeading(value, limit = 5) {
  const text = String(value || '').normalize('NFKC').replace(/\s+/g, ' ').trim();
  const output = [];
  const seenNames = new Set();
  const seenGroups = new Set();
  for (const [pattern, nameZh, ruleId, group = ''] of RULES) {
    if (group && seenGroups.has(group)) continue;
    const match = text.match(pattern);
    if (!match || seenNames.has(nameZh)) continue;
    output.push({
      nameZh,
      nameOriginal: match[0],
      rule: ruleId,
      evidenceSnippet: text.slice(0, 120)
    });
    seenNames.add(nameZh);
    if (group) seenGroups.add(group);
    if (output.length >= limit) break;
  }
  return output;
}
